[package]
name = "rustsort"
version = "0.1.0"
authors = ["colew-picaro <colevohs@gmail.com>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5"
rayon = "1.1"

[profile.dev]
opt-level = 3
